/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/

const express = require('express');
const app = express();
const bcrypt = require('bcrypt'); // ← agregado según lo solicitado

const bodyParser = require('body-parser');
const myDB = require('./connection');
const fccTestingRoutes = require('./routes/fcctesting.js');
const auth = require('./auth.js');
const routes = require('./routes.js');

app.use('/public', express.static(process.cwd() + '/public'));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

//Index page (static HTML)
app.route('/').get(function (req, res) {
  res.sendFile(process.cwd() + '/views/index.html');
});

fccTestingRoutes(app);

myDB(async client => {
  const myDatabase = await client.db('database').collection('users');

  routes(app, myDatabase);
  auth(app, myDatabase);

}).catch(e => {
  app.route('/').get((req, res) => {
    res.send('Unable to connect to database');
  });
});

module.exports = app;

























const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log("Listening on port:", PORT)
});
